// tauri-app/src/pages/ProfilePage.tsx
import React from "react";
import {
  Box,
  Paper,
  Typography,
  Button,
  Grid,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  Divider,
  Chip,
} from "@mui/material";
import {
  Person as PersonIcon,
  ExitToApp as LogoutIcon,
  Refresh as RefreshIcon,
  Info as InfoIcon,
  Settings as SettingsIcon,
} from "@mui/icons-material";

interface ProfilePageProps {
  onRefresh: () => void;
  onLogout: () => void;
}

const ProfilePage: React.FC<ProfilePageProps> = ({ onRefresh, onLogout }) => {
  const user = JSON.parse(localStorage.getItem("user") || "{}");
  const token = localStorage.getItem("token");

  const handleLogout = () => {
    onLogout();
  };

  const handleClearCache = () => {
    localStorage.clear();
    window.location.reload();
  };

  const appInfo = {
    version: "1.0.0",
    buildDate: "2024-01-01",
    environment: "production",
  };

  return (
    <Box sx={{ p: 2 }}>
      {/* User Info */}
      <Paper sx={{ p: 3, mb: 3 }}>
        <Box display="flex" alignItems="center" gap={2} mb={2}>
          <PersonIcon sx={{ fontSize: 48, color: "primary.main" }} />
          <Box>
            <Typography variant="h6" component="h1">
              {user.username || "用户"}
            </Typography>
            <Typography variant="body2" color="textSecondary">
              {user.email || "未设置邮箱"}
            </Typography>
          </Box>
        </Box>

        <Box display="flex" gap={1} flexWrap="wrap">
          <Chip
            label={`版本: ${appInfo.version}`}
            size="small"
            variant="outlined"
          />
        </Box>
      </Paper>

      {/* Actions */}
      <List>
        {token && (
          <>
            <Divider sx={{ my: 1 }} />
            <ListItem
              button
              onClick={handleLogout}
              sx={{ color: "error.main" }}
            >
              <ListItemIcon sx={{ color: "error.main" }}>
                <LogoutIcon />
              </ListItemIcon>
              <ListItemText primary="退出登录" />
            </ListItem>
            <Divider sx={{ my: 1 }} />
          </>
        )}
      </List>

      {/* System Info */}
    </Box>
  );
};

export default ProfilePage;

// tauri-app/src/pages/ProfilePage.svelte
<script>
    export let onRefresh = () => {};
    export let onLogout = () => {};

    let user = {};
    let token = "";

    import { onMount } from "svelte";
    onMount(() => {
        try {
            const userData = localStorage.getItem("user");
            if (userData) {
                user = JSON.parse(userData);
            }
            token = localStorage.getItem("token") || "";
        } catch (error) {
            console.error("Failed to parse user data:", error);
        }
    });

    function handleLogout() {
        onLogout?.();
    }

    function handleClearCache() {
        localStorage.clear();
        window.location.reload();
    }

    const appInfo = {
        version: "1.0.0",
        buildDate: "2024-01-01",
        environment: "production",
    };
</script>

<div class="profile-page">
    <!-- User Info -->
    <div class="user-card">
        <div class="user-header">
            <span class="user-icon">👤</span>
            <div class="user-details">
                <h1>{user.username || "用户"}</h1>
                <p>{user.email || "未设置邮箱"}</p>
            </div>
        </div>

        <div class="app-info">
            <span class="version-badge">版本: {appInfo.version}</span>
        </div>
    </div>

    <!-- Actions -->
    <div class="actions-section">
        {#if token}
            <div class="divider"></div>
            <button class="logout-btn" onclick={handleLogout}>
                <span class="icon">🚪</span>
                <span>退出登录</span>
            </button>
            <div class="divider"></div>
        {/if}
    </div>
</div>

<style>
    .profile-page {
        height: 100;
        overflow-y: auto;
        background-color: #f5f5f5;
        padding: 16px;
    }

    .user-card {
        background: white;
        border-radius: 12px;
        padding: 24px;
        margin-bottom: 24px;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    }

    .user-header {
        display: flex;
        align-items: center;
        gap: 16px;
        margin-bottom: 16px;
    }

    .user-icon {
        font-size: 48px;
        color: #1976d2;
    }

    .user-details h1 {
        margin: 0 0 4px 0;
        font-size: 20px;
        font-weight: 600;
        color: #333;
    }

    .user-details p {
        margin: 0;
        font-size: 14px;
        color: #666;
    }

    .app-info {
        display: flex;
        flex-wrap: wrap;
        gap: 8px;
    }

    .version-badge {
        background: none;
        border: 1px solid #1976d2;
        color: #1976d2;
        padding: 4px 8px;
        border-radius: 12px;
        font-size: 12px;
        font-weight: 500;
    }

    .actions-section {
        background: white;
        border-radius: 12px;
        overflow: hidden;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    }

    .divider {
        height: 1px;
        background-color: #e0e0e0;
        margin: 0;
    }

    .logout-btn {
        display: flex;
        align-items: center;
        gap: 12px;
        width: 100%;
        background: none;
        border: none;
        padding: 16px;
        color: #f44336;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.2s ease;
    }

    .logout-btn:hover {
        background-color: #ffebee;
    }

    .logout-btn .icon {
        font-size: 20px;
    }

    .logout-btn span {
        font-weight: 500;
    }
</style>
